export const steps = [
    { id: 1, title: "Category" },
    { id: 2, title: "Service" },
    { id: 3, title: "Team" },
    { id: 4, title: "Date & Time" },
    { id: 5, title: "Your Info" },
  ];

  export const categories = [
    {
      id: "hair",
      name: "Hair Services",
      description: "Expert styling and care",
      gradient: "bg-gradient-to-br from-blue-50 to-blue-100",
      
      iconColor: "text-blue-600",
    },
    {
      id: "beauty",
      name: "Beauty Services",
      description: "Professional beauty treatments",
      gradient: "bg-gradient-to-br from-purple-50 to-purple-100",
      iconColor: "text-purple-600",
    },
    {
      id: "massage",
      name: "Massage & Wellness",
      description: "Relaxation and therapy",
      gradient: "bg-gradient-to-br from-orange-50 to-orange-100",
      iconColor: "text-orange-600",
    },
    {
      id: "nails",
      name: "Nail Services",
      description: "Manicure and pedicure",
      gradient: "bg-gradient-to-br from-green-50 to-green-100",
      iconColor: "text-green-600",
    },
  ];

  export const services = {
    hair: [
      {
        id: "cut",
        name: "Haircut & Styling",
        description: "A haircut and styling service",
        gradient: "bg-gradient-to-br from-blue-50 to-blue-100",
        duration: "60 min",
        price: "45",
        discount: "10",
      },
      {
        id: "color",
        name: "Hair Coloring",
        description: "A hair coloring service",
        gradient: "bg-gradient-to-br from-purple-50 to-purple-100",
        duration: "120 min",
        price: "120",
        discount: "10",
      },
      {
        id: "treatment",
        name: "Hair Treatment",
        description: "A hair treatment service",
        gradient: "bg-gradient-to-br from-green-50 to-green-100",
        duration: "90 min",
          price: "80",
          discount: "10",
      },
      {
        id: "cut-2",
        name: "Haircut & Styling",
        description: "A haircut and styling service",
        gradient: "bg-gradient-to-br from-blue-50 to-blue-100",
        duration: "60 min",
        price: "45",
        discount: "10",
      },
      { 
        id: "color-3",
        name: "Hair Coloring",
        description: "A hair coloring service",
        gradient: "bg-gradient-to-br from-purple-50 to-purple-100",
        duration: "120 min",
        price: "120",
        discount: "0",
      },
      {
        id: "treatment-3",
        name: "Hair Treatment",
        description: "A hair treatment service",
        gradient: "bg-gradient-to-br from-green-50 to-green-100",
        duration: "90 min",
        price: "80",
        discount: "10",
      },
    ],
    beauty: [
      {
        id: "facial",
        name: "Facial Treatment",
        description: "A facial treatment service",
        gradient: "bg-gradient-to-br from-blue-50 to-blue-100",
        duration: "90 min",
        price: "80",
        discount: "10",
      },
      {
        id: "makeup",
        name: "Makeup Application",
        description: "A makeup application service",
        gradient: "bg-gradient-to-br from-purple-50 to-purple-100",
        duration: "60 min",
        price: "65",
        discount: "10",
      },
      {
        id: "eyebrow",
        name: "Eyebrow Shaping",
        description: "An eyebrow shaping service",
        gradient: "bg-gradient-to-br from-green-50 to-green-100",
        duration: "30 min",
        price: "25",
        discount: "10",
      },
    ],
    massage: [
      {
        id: "deep",
        name: "Deep Tissue Massage",
        description: "A deep tissue massage service",
        gradient: "bg-gradient-to-br from-blue-50 to-blue-100",
        duration: "75 min",
        price: "95",
        discount: "0",
      },
      {
        id: "relaxation",
        name: "Relaxation Massage",
        description: "A relaxation massage service",
        gradient: "bg-gradient-to-br from-purple-50 to-purple-100",
        duration: "60 min",
        price: "75",
        discount: "10",
      },
      {
        id: "hotstone",
        name: "Hot Stone Therapy",
        description: "A hot stone therapy service",
        gradient: "bg-gradient-to-br from-green-50 to-green-100",
        duration: "90 min",
        price: "110",
        discount: "10",
      },
    ],
    nails: [
      { id: "manicure", name: "Manicure", description: "A manicure service", gradient: "bg-gradient-to-br from-blue-50 to-blue-100", duration: "45 min", price: "35", discount: "10" },
      { id: "pedicure", name: "Pedicure", description: "A pedicure service", gradient: "bg-gradient-to-br from-purple-50 to-purple-100", duration: "60 min", price: "45", discount: "0" },
      { id: "nailart", name: "Nail Art", description: "A nail art service", gradient: "bg-gradient-to-br from-green-50 to-green-100", duration: "30 min", price: "20", discount: "0" },
    ],
  };
export const morningSlots = ["9:00 AM","9:30 AM","10:00 AM","10:30 AM","11:00 AM","11:30 AM","12:00 PM","12:30 PM"];
export const eveningSlots = ["4:00 PM","4:30 PM","5:00 PM","5:30 PM","6:00 PM","6:30 PM","7:00 PM","7:30 PM"];
  export const teamMembers = [
    {
      id: "sarah",
      name: "Sarah Johnson",
      specialty: "Hair Styling",
      avatar: "SJ",
      rating: 4.9,
      experience: "8+ years",
    },
    {
      id: "mike",
      name: "Mike Chen",
      specialty: "Massage Therapy",
      avatar: "MC",
      rating: 4.8,
      experience: "6+ years",
    },
    {
      id: "emma",
      name: "Emma Rodriguez",
      specialty: "Beauty Specialist",
      avatar: "ER",
      rating: 4.7,
      experience: "5+ years",
    },
  ];