import {
  JobCategory,
  JobGetSchema,
  JobStatus,
  SalaryType,
} from "@/lib/api/jobs/schema";

export const Job_Details: JobGetSchema[] = [
  {
    id: 1,
    title: "House Keeping",
    description:
      "Experienced professional with a passion for helping businesses grow through excellent customer service.",
    minimum_education: "MBA in Business Administration",
    characteristics: [
      "Patient",
      "Detail-oriented",
      "Problem-solver",
      "Empathetic",
    ],
    status: JobStatus.active,
    job_category: JobCategory.full_time,
    workers_required: 142,
    workers_hired: 48,
    salary: 12600,
    salary_type: SalaryType.hourly,
    language: ["English", "Spanish"],
    from_date_time: "2025-02-01T09:00:00.000Z",
    to_date_time: "2025-02-01T17:00:00.000Z",
  },
  {
    id: 2,
    title: "Customer Service",
    description:
      "Creative professional specializing in building long-term customer relationships.",
    minimum_education: "BS in Marketing & Communications",
    characteristics: ["Outgoing", "Persuasive", "Goal-driven", "Team player"],
    status: JobStatus.active,
    job_category: JobCategory.full_time,
    workers_required: 128,
    workers_hired: 45,
    salary: 11400,
    salary_type: SalaryType.fixed,
    language: ["English", "Mandarin"],
    from_date_time: "2025-02-02T08:00:00.000Z",
    to_date_time: "2025-02-02T16:00:00.000Z",
  },
  {
    id: 3,
    title: "Support Specialist",
    description:
      "Psychology background helps understand customer needs and provide personalized solutions.",
    minimum_education: "BA in Psychology",
    characteristics: [
      "Understanding",
      "Compassionate",
      "Active listener",
      "Supportive",
    ],
    status: JobStatus.active,
    job_category: JobCategory.full_time,
    workers_required: 115,
    workers_hired: 41,
    salary: 10500,
    salary_type: SalaryType.hourly,
    language: ["English", "Spanish", "French"],
    from_date_time: "2025-02-03T10:00:00.000Z",
    to_date_time: "2025-02-03T18:00:00.000Z",
  },
  {
    id: 4,
    title: "Data Entry Clerk",
    description:
      "Detail-oriented professional for data management and entry tasks.",
    minimum_education: "High School Diploma",
    characteristics: ["Accurate", "Fast", "Organized", "Reliable"],
    status: JobStatus.inactive,
    job_category: JobCategory.full_time,
    workers_required: 50,
    workers_hired: 20,
    salary: 8000,
    salary_type: SalaryType.fixed,
    language: ["English"],
    from_date_time: "2025-02-04T09:00:00.000Z",
    to_date_time: "2025-02-04T17:00:00.000Z",
  },
];
