import { JobSchema } from "@/types";

export const Job_Details: JobSchema[] = [
  {
    id: "1",
    job_name: "House Keeping",
    description:
      "Experienced professional with a passion for helping businesses grow through excellent customer service.",
    email: "sarah.johnson@whenwework.com",
    phone: "+1 (555) 123-4567",
    profileImage: "/customer_support.png",
    minimum_education: "MBA in Business Administration",
    tone: "professional",
    characteristics: [
      "Patient",
      "Detail-oriented",
      "Problem-solver",
      "Empathetic",
    ],
    status: "active",
    joinDate: "2023-01-15",
    people_needed: 142,
    people_hired: 48,
    salary: 12600,
    salary_type: "per_hour",
    languages: ["English", "Spanish"],
  },
  {
    id: "2",
    job_name: "Customer Service",
    description:
      "Creative professional specializing in building long-term customer relationships.",
    email: "michael.chen@whenwework.com",
    phone: "+1 (555) 234-5678",
    profileImage: "/customer_support.png",
    minimum_education: "BS in Marketing & Communications",
    tone: "friendly",
    characteristics: ["Outgoing", "Persuasive", "Goal-driven", "Team player"],
    status: "active",
    joinDate: "2023-03-20",
    people_needed: 128,
    people_hired: 45,
    salary: 11400,
    salary_type: "fixed",
    languages: ["English", "Mandarin"],
  },
  {
    id: "3",
    job_name: "Support Specialist",
    description:
      "Psychology background helps understand customer needs and provide personalized solutions.",
    email: "emily.rodriguez@whenwework.com",
    phone: "+1 (555) 345-6789",
    profileImage: "/customer_support.png",
    minimum_education: "BA in Psychology",
    tone: "empathetic",
    characteristics: [
      "Understanding",
      "Compassionate",
      "Active listener",
      "Supportive",
    ],
    status: "active",
    joinDate: "2023-05-10",
    people_needed: 115,
    people_hired: 41,
    salary: 10500,
    salary_type: "per_hour",
    languages: ["English", "Spanish", "French"],
  },
  {
    id: "4",
    job_name: "Data Entry Clerk",
    description:
      "Detail-oriented professional for data management and entry tasks.",
    email: "john.doe@whenwework.com",
    phone: "+1 (555) 456-7890",
    profileImage: "/customer_support.png",
    minimum_education: "High School Diploma",
    tone: "professional",
    characteristics: ["Accurate", "Fast", "Organized", "Reliable"],
    status: "inactive",
    joinDate: "2023-06-01",
    people_needed: 50,
    people_hired: 20,
    salary: 8000,
    salary_type: "fixed",
    languages: ["English"],
  },
];
